### ISSUE TITLE
Server connection message error

### ISSUE THREAD

**Issue by Rafirzm** [redeclipse/base#962] opened 2019-12-20 01:51 UTC
- RE 2.0
- Related discussion: redeclipse/world#ID
- Observation: No message error, zero-based knowledge
- Expected result: Error message
- How to reproduce: Try to connect to a server

```
No message is triggered for some seconds when attempting to connect so you don't see it, try to make a key updates for clearing this UI Mapping issues, kinda annoying somehow. :/
```
Edit: Incompatible protocol from RE 1.5.6

**Comment by nonoesimposible** [comment] 2019-12-20 02:15
> Incompatible protocol from RE 1.5.6

Does this mean the issue is resolved (we can close it now)? It seems that you were trying to connect to an old version of RE with the newly released 2.0.

**Comment by molexted** [comment] 2019-12-20 03:06
Yeah, this is just a clearly incompatible protocol. The server browser will flat out tell you that there is an invalid protocol on the server, so there isn't a UI clarity issue either.

**Closed by molexted** 2019-12-20 03:06 UTC
Labels: triage

**Comment by Rafirzm** [comment] 2019-12-20 05:42
It doesn't tell the user of the program the error done at the attempt to connect, the person is unable to read what has been done by the program when connecting to a server in the UI of the 2.0^^

**Comment by molexted** [comment] 2019-12-20 05:46
You have to *enable* showing incompatible servers in RE2. It should be obvious that these incompatible servers are incompatible with the game.

Default configuration with settings wiped: 
![20191219214528](https://user-images.githubusercontent.com/23445929/71232974-edeffe80-22a8-11ea-9f13-658f1604c55f.png)

Incompatible servers won't show up unless you explicitly ask to see them.

**Comment by qreeves** [comment] 2019-12-21 05:11
Moving to `world` as this isn't a bug and `base` isn't the appropriate place for technical support.
