### ISSUE TITLE
Grenades can be recooked by reloading or switching weapons

### ISSUE THREAD

**Issue by molexted** [redeclipse/base#829] opened 2018-07-07 19:20 UTC
This one is both true in the stable and master versions.
Grenades can have their timer reset by pressing the R key or switching weapons, allowing for a weapon which should be a one-shot weapon to be saved if the target slips out of range.

Normally, grenades are set to explode a certain time after the pin is pulled and cannot be reset; it seems reasonable to enforce that here. The wiki entry on the grenade as well as the  f1 help menu entry implies that the grenade is nominally a one shot, one kill weapon.

The simplest way to fix this is probably to toss the grenade upon attempting to reload or switch weapons.

**Comment by IceflowRE** [comment] 2018-07-07 19:31
I wouldnt confirm this as a bug...
Its a nice way to break the cooking and dont let the grenade explode. Why you it should not be allowed to reset it?

Its a topic to discuss.

**Comment by molexted** [comment] 2018-07-07 19:36
Because the documentation doesn't imply that this is valid behavior, and real grenades can do nothing of the sort. It's unintuitive and hacky to suggest that by switching weapons you just put a primed grenade in your back pocket for later, and if this indeed intended behavior, then the help menu should explicitly state that.

**Comment by IceflowRE** [comment] 2018-07-07 20:08
`real grenades can do nothing of the sort.`
RE does not try to be real.
`It's unintuitive and hacky to suggest that by switching weapons you just put a primed grenade in your back pocket for later`
Where should the grenade go else, if you put out another weapon? of course it goes back. And at least if you did it once you know it.
`if this indeed intended behavior, then the help menu should explicitly state that.`
Yes, the help menu could include a hint like: `Tip: changing your weapon or reloading will break the cooking mode.`

**Comment by molexted** [comment] 2018-07-07 20:33
> RE does not try to be real.

It actually does in many respects; the submachine gun takes 40 round clips like a typical submachine gun; the shotgun requires adding shells like a typical shotgun, and the pistol takes 10 bullets like a typical (if dated) handgun. If you present a weapon which is superficially similar to a real weapon, there are certain expectations as to its abilities. 
My biggest problem with having recookable grenades is not that it is particularly immersion breaking or overpowered, but that it is an unexplained perk that unfairly disadvantages novices with no particular reason to believe they can stuff a live grenade away for later. Even adding an entry into the f1 menu is probably mostly pointless, since nobody reads the documentation anyway. It's the implied baggage that comes with being called a "grenade" that saddles it with particular attributes.

> Where should the grenade go else, if you put out another weapon?

> The simplest way to fix this is probably to toss the grenade upon attempting to reload or switch weapons.

**Comment by swooboo** [comment] 2018-07-07 21:17
My 2 cents. Currently, grenade is useful, but barely. Most grenades do little to no damage because it's hard to actually land a hit. If we go through with the suggestion of @molexted, the grenade will be nerfed greatly, which in turn make it virtually useless. So while I agree that the current behavior is unintuitive, I'm still against the nerf.

As for unfairly disadvantaging novices, they will learn this behavior quickly after specc'ing somebody or even playing against a player executing the move.

**Comment by SniperGoth** [comment] 2018-07-07 21:47
Ah, this isn't considered a bug afaik, more of a feaure, because this is known since a looooong time, and was never changed.
I'd leave it as it is.

**Comment by qreeves** [comment] 2018-07-08 05:06
Yeah, this ability came about when we allowed certain actions to interrupt others (eg. reloading then interrupting that to switch weapons). It is considered to be intended behaviour and what the grenade has been modelled after over the years (it used to be about as powerful as a rocket).

Personally, I use this ability very frequently because often the situation you initially cooked the grenade for has drastically changed due to the immense speed of the game (but of which is different in 2.0). It allows for a sort of "retry" where you can make a better estimate, but it does take a little bit of time to do the interrupt before being able to cook again.

It could be changed for 2.0, but I'd *really* suggest a poll for this one. That being said, I don't think it is a candidate for 1.6.

**Comment by acerspyro** [comment] 2019-02-09 20:25
I believe this should be fixed (as it is, as @molexted mentioned, an unintended operation) and then allowed through a variable.

What's fun about Red Eclipse is that anyone can decide what properties they want their server to reflect. ^.^

If we take this logical route, the remaining question is now whether this should be default behaviour or not.

**Comment by Calinou** [comment] 2019-02-09 21:31
As grenades don't seem that powerful to me (against skilled players), I think the current behavior can be kept.

(For what it's worth, grenades work the same in Counter-Strike, and it's considered far more realistic than Red Eclipse :upside_down_face:)

**Comment by lambda-11235** [comment] 2019-02-10 09:27
I think it should be kept. While it's true that real grenades can't be uncooked, real people can't spontaneously move at 30+ mph. I think for non-recookable grenades to be useful the cook time would have to be reduced, so one could expect to hit a target the moment they decide to arm the grenade.

**Comment by qreeves** [comment] 2019-10-20 21:47
This has now been implemented with `cookinterrupt`

**Closed by qreeves** 2019-10-20 21:47 UTC
Labels: branch: master, status: please discuss further
