### ISSUE TITLE
Face-capture vertex stretching

### ISSUE THREAD

**Issue by AdamantiteMachine** [redeclipse/base#1076] opened 2020-07-12 05:18 UTC
- Version and build: [2.0.0] [Selfbuilt]
- Related discussion: redeclipse/world#ID
- Observation: [Weird vertex stretching caused by the teleporter entities.]
- Expected result: [None of that.]
- How to reproduce: [Import Sauerbraten map "Face-capture", it'll have that problem without any changes.]

Stretched vertex
![2020-07-12_04-48](https://user-images.githubusercontent.com/52565291/87239449-c3a98e00-c3fe-11ea-9053-50d459bd374b.png)

Stretched vertex [Highlighted]
![2020-07-12_04-47](https://user-images.githubusercontent.com/52565291/87239452-d02de680-c3fe-11ea-9bc0-84ac6fa84de9.png)

Map file, ready to use in Red Eclipse.
[FacingAbug.zip](https://github.com/redeclipse/base/files/4908042/FacingAbug.zip)

**Comment by Dziq84** [comment] 2020-07-12 08:53
found this in a minute ;p,  `/entfind teleport`,  then `/entattr 4 0` fixes the issue
I do not recall that teleports have color attribute.. what is used for?

**Comment by Jigoku** [comment] 2020-07-12 14:03
Prior to 1.6, the teleports have a particle drawn when the colour/palette is set, using this texture: https://github.com/redeclipse/particles/blob/5f98a74fac608a21e4c33c412015898013f6ac13/teleport.png 

AFAIK it hasn't been drawn correctly since 1.6 was released (maybe earlier versions too). I personally thought that the teleport particle being absent was intended, but turns out it is indeed a bug.

**Comment by Jigoku** [comment] 2020-09-29 08:14
My guess is the transformation is off here: https://github.com/redeclipse/base/blame/b0ae6073de25769df123a9cdcbd820da9c497cce/src/engine/renderparticles.cpp#L449-L457

**Comment by Jigoku** [comment] 2022-02-08 18:45
Just checked now as for some recent changes to teleports; has been fixed in e67e4f37f0fd3287734bc6e7ff2eb16f527dc67d

**Closed by Jigoku** 2022-02-08 18:45 UTC
Labels: status: bug
