### ISSUE TITLE
Grenades Sticky Mode sometimes will stay in air.

### ISSUE THREAD

**Issue by ghost** [redeclipse/base#1239] opened 2021-02-23 15:04 UTC
If I throw a grenade in secondly mode to another player, but he has gone away before the grenade attached, the grenade will stay in air before explode.

**Comment by chantianz** [comment] 2021-02-27 03:28
This bug appears in 2.0.0 Master 2978.

**Comment by Jigoku** [comment] 2021-02-28 02:11
I would guess it could be related to this old issue: 
https://github.com/redeclipse/base/issues/116

**Comment by qreeves** [comment] 2022-10-22 11:19
Closing as duplicate of #116

**Closed by qreeves** 2022-10-22 11:19 UTC
